version: 2

updates:

  # .NET SDK 
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # NPM (Vue.js Client app)
  - package-ecosystem: "npm"
    directory: "/src/RKTimeTrack.Service/ClientApp"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Nuget for all .NET projects   
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.Application"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.Application.Tests"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.FileBasedTimeTrackingRepositoryAdapter"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.FileBasedTimeTrackingRepositoryAdapter.Tests"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.Service"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.Service.IntegrationTests"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.StaticTopicRepositoryAdapter"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/RKTimeTrack.StaticTopicRepositoryAdapterTests"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"